### ISSUE TITLE
thoughts on natural sort recognizing roman numerals?

### ISSUE THREAD

**Issue by wez** [Aloso/lexical-sort#12]
I'm not sure if you'd go for this, but it can't hurt to ask!
What do you think about teaching the natural number sorting logic recognizing roman numerals?

I'm currently doing this by pre-processing the string by splitting on whitespace, parsing roman numerals and replacing them with arabic/decimal integers. It works, but is relatively heavyweight.

![image](https://github.com/Aloso/lexical-sort/assets/117777/fd36b0e7-40df-423e-8606-80afcab529d1)

**Comment by Aloso** [comment]
I don't think this feature is a good fit for this crate. Also, this crate isn't actively maintained and doesn't receive new features anymore. I would recommend using the [icu_collator](https://docs.rs/icu_collator/latest/icu_collator/) crate instead. It has more features, is more correct, and locale-sensitive. It doesn't support roman numerals either, probably because it is a very uncommon requirement.
